name: Run Unit Test(Jest)

on:
    push:
        branches:
            - main
            - dev
    pull_request:
        types: [opened, synchronize, reopened]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '22.14.0'

            - name: Install dependencies
              run: npm install

            - name: Run Jest tests
              run: npm run test
